import Head from 'next/head';
import { inter } from '@/styles/fonts';
import styles from './Layout.module.scss';



const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>Next.js Boilerplate</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={`${styles.main} ${inter.variable}`}>
				<div className={styles.container}>
					{children}
				</div>
			</main>
		</>
	)
}

export default Layout;
